version: "3.8"
services: 
    mysql:
        container_name: mysql
        image: mysql-logrotate
        build:
            context: ./mysql-logrotate
            dockerfile: Dockerfile
        environment: 
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - "3307:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
            - ./backups:/backups